# Changes here will be overwritten by Copier
"_commit": "a7efa7f"
"_src_path": "https://github.com/stepmanai/base-template.git"
"project_description": "A time series extrinsic regression model built to objectively measure stepfile difficulty in community-based vertical scroll rhythm games."
"project_name": "ACubed"
