# Changes here will be overwritten by Copier
"_commit": "905521c"
"_src_path": "https://github.com/stepmanai/project-bass.git"
"project_description": "A time series extrinsic regression model built to objectively measure stepfile difficulty in community-based vertical scroll rhythm games."
"project_name": "ACubed"
