# Changes here will be overwritten by Copier
"_commit": "5db6ed2"
"_src_path": "https://github.com/stepmanai/project-bass.git"
"project_description": "A model training framework for building stepfile difficulty prediction models for open source rhythm games."
"project_name": "ACubed"
